[
        "Judge The Sentiment Of Youtube Comment",
        "Extract Amazon",
        "Box People And Signs In An Image",
        "Format 4 -",
        "Business Relationships Research",
        "Supplier Locations",
        "Box And Transcribe Text In An Image",
        "Document Recognition And Translations (Cf Redesign)",
        "Unit Of Measure Annotation",
        "Production- External M&A External Event Detection - High Quality",
        "Object/Keyword Identification & Image Style For Ads",
        "Keyword Identification & Image Style For Ads",
        "What Product Information Is Most Important To Your Buying Decision For Storage Sheds?",
        "Is This A Sponsored",
        "Image Description And Relevant Words",
        "Quick & Easy- Caulk Video Survey",
        "Annotate And Categorize Objects In An Image Using A Bounding Box",
        "Outline Objects In Images With Polygons",
        "Pick The Most Similar Company",
      //  "Identify The Bill Of Lading Number (Cf Revision)",
        "Google Search For Employee Name, Job Title And Linkedin Url Collection Assistance",
        "Detecting Student Engagement In Online Classes",
        "Welcome To Appen",
        "Classify Web Pages With Adult (Potential Explicit Content)",
        "Classify Web Pages With Drugs Content",
        "Annotate Text By Tokens Or Spans",
        "Classify Web Pages With Offensive Language",
        "Classify Web Pages With Hate Speech",
        "Rate Ai Responses According To Their Quality",
        "Interior Lighting Video And Image Customer Preference | Audio Required",
        "The Henry Company Image Impact Survey",
        "Cordless Power Equipment",
        "Quick & Easy Image Survey - Portable Power Accessories (Ranking Images)",
        "Model Response Comparison - V40 (A/B/Neither Only Eval)",
        "Model Response Comparison - V40 (A/B/Neither Only Eval)",
        "Banner Quality Test",
        "Rationale Correction",
        "Cabinet Knob Image Survey",
        "Cabinet Pull Image Survey",
        "Market Research Job",
        "Find The Official Website Of Businesses - 2021-10-05",
        "Uk_search-Science",
        "2Fa Ops Overhaul"
    ];
